name: Azure Deployment

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: lokchabot.azurecr.io
          username: lokchabot
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend Docker image
        working-directory: backend
        run: |
          docker build -t lokchabot.azurecr.io/backend:${{ github.run_id }} .
          docker push lokchabot.azurecr.io/backend:${{ github.run_id }}

      - name: Build and push frontend Docker image
        working-directory: frontend
        run: |
          docker build -t lokchabot.azurecr.io/frontend:${{ github.run_id }} .
          docker push lokchabot.azurecr.io/frontend:${{ github.run_id }}

      - name: Deploy Backend to Azure App Service
        run: |
          az webapp config container set --name lokbackendchatbot --resource-group b15-Lok --docker-custom-image-name lokchabot.azurecr.io/backend:${{ github.run_id }}

      - name: Deploy Frontend to Azure App Service
        run: |
          az webapp config container set --name lokbackendchatbot --resource-group b15-Lok --docker-custom-image-name lokchabot.azurecr.io/frontend:${{ github.run_id }}
