name: Azure Deployment

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: lokbotchat.azurecr.io
          username: lokbotchat
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend Docker image
        working-directory: backend
        run: |
          docker build -t lokbotchat.azurecr.io/backend:${{ github.run_id }} .
          docker push lokbotchat.azurecr.io/backend:${{ github.run_id }}

      - name: Build and push frontend Docker image
        working-directory: frontend
        run: |
          docker build -t lokbotchat.azurecr.io/frontend:${{ github.run_id }} .
          docker push lokbotchat.azurecr.io/frontend:${{ github.run_id }}

      - name: Deploy Backend to Azure Container Instances
        run: |
          az container create \
          --resource-group loke60000 \
          --name lokapi-adabot-backend \
          --image lokbotchat.azurecr.io/backend:${{ github.run_id }} \
          --dns-name-label lokapi-adabot-backend-${{ github.run_id }} \
          --ports 8000 \
          --registry-username lokbotchat \
          --registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Deploy Frontend to Azure Container Instances
        run: |
          az container create \
          --resource-group loke60000 \
          --name lokapi-adabot-frontend \
          --image lokbotchat.azurecr.io/frontend:${{ github.run_id }} \
          --dns-name-label lokapi-adabot-frontend-${{ github.run_id }} \
          --ports 8001 \
          --registry-username lokbotchat \
          --registry-password ${{ secrets.ACR_PASSWORD }}
